export default [
    {
        id:crypto.randomUUID(),
        title:'milk',
        category:'Groccery',
        amount:40
    },
    {
        id:crypto.randomUUID(),
        title:'shirt',
        category:'Clothes',
        amount:400
    },
    {
        id:crypto.randomUUID(),
        title:'veggies',
        category:'Groccery',
        amount:100
    },
    {
        id:crypto.randomUUID(),
        title:'headphone',
        category:'Electronics',
        amount:800
    }
]